"""password length rectified

Revision ID: 915acd13293b
Revises: d67b2bcd1119
Create Date: 2025-05-21 20:02:29.686727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915acd13293b'
down_revision = 'd67b2bcd1119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
